---
name: Publish documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish documentation
    runs-on: nebula-runners
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PID0030PAT }}
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          cd tutorial
          pip install mkdocs-material
          pip install -r requirements.txt
          mkdocs gh-deploy --force -s
