name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - run: |
          cd docs
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-material-extensions
          mkdocs build
          mkdocs gh-deploy --force --clean --verbose    

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          CONFIG_FILE: docs/mkdocs.yml