name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - run: |
          cd docs
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-material-extensions
          mkdocs build
          mkdocs gh-deploy
